[build]
target = "aarch64-unknown-none-softfloat"


[target.aarch64-unknown-none-softfloat]
rustflags = ["-C", "link-arg=-T./src/bsp/raspberrypi/link.ld"]
runner = "src/bsp/raspberrypi/qemu_runner.sh"
